spring.application.name=rcmu
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/tu_db
spring.datasource.username=tu_user
spring.datasource.password=tu_password